# This rule is not used by the project k8s-mend itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over reliability.platform.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-mend
    app.kubernetes.io/managed-by: kustomize
  name: selfhealingpolicy-admin-role
rules:
- apiGroups:
  - reliability.platform.ai
  resources:
  - selfhealingpolicies
  verbs:
  - '*'
- apiGroups:
  - reliability.platform.ai
  resources:
  - selfhealingpolicies/status
  verbs:
  - get
