# This rule is not used by the project k8s-mend itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to reliability.platform.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-mend
    app.kubernetes.io/managed-by: kustomize
  name: selfhealingpolicy-viewer-role
rules:
- apiGroups:
  - reliability.platform.ai
  resources:
  - selfhealingpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reliability.platform.ai
  resources:
  - selfhealingpolicies/status
  verbs:
  - get
