apiVersion: reliability.platform.ai/v1alpha1
kind: SelfHealingPolicy
metadata:
  labels:
    app.kubernetes.io/name: k8s-mend
    app.kubernetes.io/managed-by: kustomize
  name: selfhealingpolicy-sample
spec:
  # TODO(user): Add fields here
